name: Running Code Coverage
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.9.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.9
    - name: Install dependencies
      run: |
        pip install pytest-cov
        pip install -r requirements.txt
        echo requirements installed
    - name: Run the tests
      run: |
          cd test
          pytest --cov=./
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
